site_name: parks-irrigation
nav:
  - Home: index.md
theme:
  name: material
  favicon: https://cdn0.iconfinder.com/data/icons/citycons/150/Citycons_park-512.png
  logo: https://cdn0.iconfinder.com/data/icons/citycons/150/Citycons_park-512.png
  font:
    text: Roboto
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - header.autohide
plugins:
  - search
  - tags
  - glightbox:
      auto_caption: True
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
markdown_extensions:
  - attr_list
  - md_in_html
