site_name: ezapi-icc-pro-demo
site_author: Zeheng Li
nav:
  - Home: index.md
theme:
  name: material
  favicon: https://cdn0.iconfinder.com/data/icons/citycons/150/Citycons_park-512.png
  logo: https://cdn0.iconfinder.com/data/icons/citycons/150/Citycons_park-512.png
  font:
    text: Roboto
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.top
plugins:
  - search
  - tags
  - glightbox:
      auto_caption: true
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
markdown_extensions:
  - attr_list
  - md_in_html
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zehengl
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/zehengl
repo_name: ezapi-icc-pro-demo
repo_url: https://github.com/zehengl/ezapi-icc-pro-demo
